name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - run: npm ci 

      # Install Angular CLI globally
      - run: npm install -g @angular/cli

      # Create environment.prod.ts dynamically using GitHub Secret
      - run: |
          mkdir -p src/environments
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  googleApiKey: '${{ secrets.GOOGLE_MAPS_API_KEY }}'" >> src/environments/environment.prod.ts
          echo "  firebase: '${{ secrets.FIREBASE_CONFIG }}'" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      # Build the project
      - run: ng build --configuration=production

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEMORISE_910C3 }}
          channelId: live
          projectId: memorise-910c3
